name: Dependabot Auto merge

on:
  pull_request:
    
jobs:
  auto-merge:
    if: ${{ github.event.label.name == 'dependencies' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
